##### NOTE THIS IS NOT THE MAIN MACRO FILE
# I made a master_geantgen.mac file which is designed to run
# with the generate-mac script located in {UCNA_BASE}/scripts
# This is an example xuan_geantgen.mac which is copied over to UCN-build
# in case you want to do some quick .mac work. For multi-thread simulations
# use the generate-mac script.

###### Pre-initialization commands
# spectrometer decay trap geometry name
/detector/geometry 2011/2012
# detector vacuum pressure
/detector/vacuum 1.e-5 torr

/detector/sourceholderpos 0 0 0 m
/detector/sourceholder false		# either place source holder in world or not
					# this ^^ is very dependent on the file type of /particleGun/inputName
# choose type of ptcl to fire (options: external, Sn113, Ce139, Bi207)
/particleGun/ptclType external	# external means we have an external file to read from.

# extra pre-initialization commands here
/detector/sourcefoilthick 9.5 um
/detector/rotation 0.037
/detector/offset -3.98 0.44 0 mm

# Supply the full path to input ptcl file, and names of the output files
/particleGun/inputName /home/xuansun/Documents/Caltech/UCNA_Sim/ucna_g4_2.1/UCN/EventGenTools/Sn113_o_p/Evts_0.root
/particleGun/outputName UCNASimOutput_test.txt	# Note: these two output names (and paths)
/event/outputName UCNASimOutput_test.txt		# need to be identical

###### Run initialization and start

/run/initialize
/run/beamOn 100
